version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin123"
      MINIO_REGION_NAME: "us-east-1"
    ports:
      - "9087:9000"
      - "9088:9001"
    volumes:
      - minio_data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  minio_data:
