version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Abc242526@2"
      TZ: "America/Sao_Paulo"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - sqlserver-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager


volumes:
  sqlserver-data:
    driver: local

networks:
  sqlserver-net:
    driver: overlay
